export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  INTRADAY: 'EMPLOYEE',
  CLIENT: 'CLIENT',
};
export const MARKET_CALL_TYPES = {
  SHORT_TERM: 'SHORT_TERM',
  LONG_TERM: 'LONG_TERM',
  INTRADAY: 'INTRADAY',
};
