export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  EMPLOYEE: 'EMPLOYEE',
  CLIENT: 'CLIENT',
};
export const MARKET_CALL_TYPES = {
  INTRADAY: 'Intra Day',
  SHORT_TERM: 'Short Term',
  LONG_TERM: 'Long Term',
};

export const MARKET_CALL_TYPES_SERVER = {
  INTRADAY: 'INTRADAY',
  SHORT_TERM: 'SHORT_TERM',
  LONG_TERM: 'LONG_TERM',
};

export const CLIENT_TYPE = {
  DISCRETIONARY: 'DISCRETIONARY',
  NON_DISCRETIONARY: 'NON DISCRETIONARY',
};

export const CLIENT_TYPE_SERVER = {
  DISCRETIONARY: 'DISCRETIONARY',
  NON_DISCRETIONARY: 'NON_DISCRETIONARY',
};

export const RESPONSE_STATUS = {
  INITIATED: 'INITIATED',
  COMPLETE: 'COMPLETE',
  REJECTED: 'REJECTED',
};
